### ISSUE TITLE
Error: permission_denied: Client doesn't have permission to access the desired data

### ISSUE THREAD

**Issue by brgnepal** [simplyaccessible/angular-a11y-ticket-tracker#1]
Hi,

I am trying to setup this project locally.
I had account in firebase and followed 2 steps mentioned in README for setting `FbURL` in `app.js`.

While opening the `index.html` page, I am getting following error.

```
 FIREBASE WARNING: on() or once() for / failed: Error: permission_denied: Client doesn't have permission to access the desired data. 
angular.js:9563 Error: permission_denied: Client doesn't have permission to access the desired data.
    at Error (native)
    at Zb (http://localhost:8000/app/bower_components/firebase/firebase.js:44:333)
    at http://localhost:8000/app/bower_components/firebase/firebase.js:114:200
    at http://localhost:8000/app/bower_components/firebase/firebase.js:82:207
    at id.h.dc (http://localhost:8000/app/bower_components/firebase/firebase.js:87:104)
    at Xc.dc (http://localhost:8000/app/bower_components/firebase/firebase.js:78:364)
    at Q.Qd (http://localhost:8000/app/bower_components/firebase/firebase.js:76:280)
    at Ec (http://localhost:8000/app/bower_components/firebase/firebase.js:60:234)
    at WebSocket.W.onmessage (http://localhost:8000/app/bower_components/firebase/firebase.js:59:111)
angular.js:9563 destroy called for FirebaseArray: https://MyFBUrl.firebaseio.com
```

What might be issue here? Am I missing something?

![accessibilit](https://cloud.githubusercontent.com/assets/1132451/7159316/e873513a-e39e-11e4-9690-8b12e38c888b.png)

**Comment by gavinogston** [comment]
Hi,

I feel like it could be two things. 

1) You are not using a valid firebase database url. (Did you create your own personal firebase database through their interface) I see the error shows "https://MyFBUrl.firebaseio.com" which seems like it might be taken already. Maybe try creating a new database.
2) Perhaps try just creating a ticket by clicking the  "Add new ticket" button, after that the error might disappear with one record in the database.

Let me know how it goes.

**Comment by brgnepal** [comment]
Hi @gavinogston ,

It was my `security & rules` issue.

Previously, I had set it based on my some other app which I empty it completely as:

```
{
    "rules": {           
    }
}
```

which was creating the problem.

Setting above to default one as below resolved the issue.

```
{
    "rules": {    
        ".read": true,
        ".write": true
    }
}
```

Thanks

**Comment by sorcamarian** [comment]
https://firebase.google.com/docs/database/security/quickstart#sample-rules

**Comment by mpeguero** [comment]
If you do this:
`{
    "rules": {    
        ".read": true,
        ".write": true
    }
}`
This will open your database to the public. anybody can make change to your 
database.
`".read": "(auth != null)",
        ".write":"(auth != null)",
}`
this is better solution. be sure to not let any subscribe method alive before logout.

**Comment by rajjerry** [comment]
I have angularfire2 and now when I change my firebase rules 
".read": "(auth != null)", ".write":"(auth != null)" and than it gives me error
Error: permission_denied at /Customer/-KaBgFKQja3QgpAbePQI/Folder: Client doesn't have permission to access the desired data.

**Comment by mpeguero** [comment]
If you are subscribing a observer on the ngDestroy method you should destroy the subcription


    this.subscription =  yourservice.method()

          .subcribe( data ==> {

                   this.mydata = data

     });



ngDestroy(){

      this.subcription.unsubscribe();

}



Hope it can help you

________________________________

**Comment by rajjerry** [comment]
yes i am unsubscribe on ngDestroy..and in subscription method i call init method which have get data api....i have use emitterservice

**Comment by mpeguero** [comment]
Other solution is that you could use the internal angular pipe "async". With async you do not need to subscribe the observer.


If you still getting that error there is somewhere a subscriber open. Check that out.

________________________________

**Comment by ivent** [comment]
Hello I've struggled until I find a solution, you need to do the Destroy on all references that link your app to firebase, usually they are linked with $ firebaseArray, $ firebaseObject to know which ones you can use this code:

```
ref.once('value', function(snapshot) {
  console.log(snapshot.val());
});
```

So it will list all the connections so, each app has a specific way of doing the disconnect but I will show below how I logout in my ex:

I created a service to pull the os $firebaseArray, $firebaseObject

app.js

```
App.factory('Users', function($firebaseArray, $firebaseObject){ 

  var ref = new Firebase('https://myfire.firebaseio.com');
  var refUsersArray = $firebaseArray(ref);
  var refUsersObject = $firebaseObject(ref);
  
  
  return {
    getUsers: function(){ 	
	  if(refLocaisArray) {
		  return $firebaseArray(ref.child('users'));
	  }
    },
    setUser: function(localId){		
		if(refLocaisObject) {
		 return $firebaseObject(ref.child('users').child(usersId));
	  }	  
    },
  destroyUsers: function(){
		refUsersArray.$destroy();
		refUsersObject.$destroy();
	}
}  
})
```

em controlles.js

```
$scope.users= Users.getUsers();	

$scope.logout = function(){
								
			firebase.onAuth(function(authData) {
			if (authData) {				
				myUuid 		= authData.uid;
				markersRef.child(myUuid).set(null)
			}				
			});
			
			// Destroy Users
			$scope.users.$destroy();			
			Users.destroyUsers();
			
			$state.go('login');
			
			firebase.unauth(); 			
			
		};
```


I hope it can help anyone who has the same problem.

**Comment by elvismercado** [comment]
@ivent any idea which ref i need to destroy when using ionic2?

**Comment by ivent** [comment]
Hello @elvismercado  I'm still starting with ionic2 however the logic is the same just check the new api from the firebase I believe they've even solved this problem.

**Comment by elvismercado** [comment]
@ivent I've updated to latest versions and have looked in the docs. Still won't work for me.

**Comment by mpeguero** [comment]
Make sure you're destroying the subscriber before logout.


If you're using Observer there an Interface that you can implement.


import { Subcription } from 'rxjs/Subcription';


private sub: Subscription;



ngOnInit(){

   this.sub = yourservice().subscribe((data)=> this.obs = data)

}


ngOnDestroy(){

   this.sub.unsubscribe();

}

________________________________

**Comment by LiveLikeCounter** [comment]
@mpeguero , good description. Question, do you know or can you make a example how to detect any subscriptions who not being unsubscribed on the page?

**Comment by mpeguero** [comment]
When I came across with this issue I just checked out all subscriptions and ensured to unsubscribe all of them.  I'm not sure is there any way to verify if any subscription is opened.

**Comment by mpeguero** [comment]
Are you using  Firebase.auth().authState and subscribe to it. It still trying to connect even though your already logged out.  Instead use Firebase.auth().auth.onAuthStateChanged.

In your methods. Do not user  FirebaseListObservable, instead use Observable<any[]>

**Comment by rsilva1959** [comment]
It's ugly, but works:

  signOut(): void {
    this.router.navigate(['/app').then(() => {
      firebase.database().goOffline()
      this.afAuth.auth.signOut()
    })
  }

**Comment by azamalvi** [comment]
@rsilva1959 you saved my day 🥇

**Comment by hamzahamidi** [comment]
**firebase.database().goOffline()** is the key to solve this problem. This will disconnect from the server (all Database operations will be completed offline).

**Comment by tvviem** [comment]
If you want test easy in dev project, you can use:
```
{
  "rules": {
    ".read": "true",
    ".write": "auth != null"
  }
}
```
You can read data anywhere, but writen data authenticated required

**Comment by procheta1999** [comment]
Will this error persist after the deployment of the site ? I mean, the users will also see this error after deployment ?
